language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.4
  - 2.3.3
  - 2.4.2
  - 2.5.0
cache: bundler
sudo: false

before_install:
  - 'echo ''gem: --no-document'' > ~/.gemrc'

script: bundle exec rake travis
